- name: Cek apakah Secret terbaca
  env:
    GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  run: |
    if [ -z "$GOOGLE_CREDENTIALS" ]; then 
      echo "❌ Secret GOOGLE_CREDENTIALS tidak ditemukan!"
      exit 1
    else
      echo "✅ Secret GOOGLE_CREDENTIALS berhasil ditemukan."
    fi
